### ISSUE TITLE
Trouble installing schema-automator into semantic-synbio/synbio-schema

### ISSUE THREAD

**Issue by turbomam** [linkml/schema-automator#100]
> Because schema-automator (0.2.8) depends on linkml (1.3.0)
and no versions of schema-automator match >0.2.8,<0.3.0, schema-automator (>=0.2.8,<0.3.0) requires linkml (1.3.0).
So, because synbio-schema depends on both schema-automator (^0.2.8) and linkml (>=1.3.4,<2.0.0), version solving failed.

**Comment by sierra-moxon** [comment]
Hi @turbomam  - I fixed this issue in https://github.com/linkml/schema-automator/pull/96 and just released a new version of schema-automator this morning (forgot to create a release).  My repo passes this error now with the new release (I am working on syncing up schemasheets version dependency in our cookie cutter repo and with bioregistry as well).   Are you using schemasheets in synbio-schema?

**Comment by turbomam** [comment]
thanks. no, I am not using schemasheets in synbio-schema. In fact I just removed it from pyproject.toml.
