### ISSUE TITLE
General debugging in advance of ICBO 2021

### ISSUE THREAD

**Issue by turbomam** [linkml/schema-automator#12]
- [ ] failures in `one_enum_to_ols_frame_list` in `enum_annotator.py` if there is no response to an OLS query (zero hits, 4xx)

**Comment by sierra-moxon** [comment]
@turbomam - I think this might be code specifically for ICBO?  (if not, I found a reference to one_enum_to_ols_frame_list in the pre-poetry directory of schema-automator, but I am not sure this directory is part of the "supported" schema-automator package.  So I think we can close for now?  Please do of course reopen if I got this wrong.
