### ISSUE TITLE
Python 3.12 not supported

### ISSUE THREAD

**Issue by Silvanoc** [linkml/schema-automator#134]
**Describe the bug**
Support for Python 3.12 is claimed in the PIP package, but is missing.

**To Reproduce**
Try to install it on a system with Python 3.12.

Observe following error:
```
  • Installing semsimian (0.2.12): Failed

  RuntimeError

  Unable to find installation candidates for semsimian (0.2.12)

  at ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/installation/chooser.py:73 in choose_for
       69│
       70│             links.append(link)
       71│
       72│         if not links:
    →  73│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       74│
       75│         # Get the best link
       76│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       77│

Cannot install semsimian.
```

**Expected behavior**
Installation succeeds.

**Additional context**
The installation fails due to dependencies that cannot be installed on Python 3.12:
* `schema-automator` [depends on `oaklib >=0.5.25`](https://github.com/linkml/schema-automator/blob/c743fd0b38d529290a1685da30ab99fe26741132/pyproject.toml#L26)
* `oaklib` [depends on `semsimian ^0.2.1`](https://github.com/INCATools/ontology-access-kit/blob/15bf85cefc2fe8541b38aabfcf7c65eb46bc1231/pyproject.toml#L38)
* no build of `semsimian` exists for Python 3.12, currently [builds exist for 3.7 =< Python =< 3.11](https://github.com/monarch-initiative/semsimian/blob/0ae82eb20c169037344de1bcbb5523a1887c95f7/.github/workflows/release.yml).

**Comment by dalito** [comment]
I tested version 0.5.2 with Python 3.12 and all issues seem to gone. Feel free to re-open.
