### ISSUE TITLE
rdflib and other pip incompatibilities

### ISSUE THREAD

**Issue by turbomam** [linkml/schema-automator#14]
I believe rdflib conflicts are already under discussion in the LinkML community? The click conflict is new to me. I've been doing some of my development on an Ubuntu 20 desktop recently.

`(venv) mark@nuc-two-ups:~/gitrepos/linkml-model-enrichment$ pip install -r requirements.txt`

> ...
ERROR: linkml-runtime 1.1.2 has requirement rdflib~=5.0, but you'll have rdflib 6.0.2 which is incompatible.
ERROR: sparqlslurper 0.4.1 has requirement rdflib~=5.0, but you'll have rdflib 6.0.2 which is incompatible.
ERROR: pyshexc 0.8.3 has requirement rdflib~=5.0, but you'll have rdflib 6.0.2 which is incompatible.
ERROR: pyshex 0.7.20 has requirement rdflib~=5.0, but you'll have rdflib 6.0.2 which is incompatible.
ERROR: linkml 1.1.9 has requirement click~=7.0, but you'll have click 8.0.3 which is incompatible.
ERROR: linkml 1.1.9 has requirement rdflib~=5.0, but you'll have rdflib 6.0.2 which is incompatible.
ERROR: funowl 0.1.9 has requirement rdflib>=5.0.0,~=5.0, but you'll have rdflib 6.0.2 which is incompatible.
...

**Comment by turbomam** [comment]
`pip install wheel` _doesn't hurt_

**Comment by turbomam** [comment]
`linkml-model-enrichment$ tsv2linkml --output ../synbio-schema/util/query_results/synbio_part.yaml  --class_name synbio_part ../synbio-schema/util/query_results/parts.tsv`

> Traceback (most recent call last):
  File "/home/mark/gitrepos/linkml-model-enrichment/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/home/mark/gitrepos/linkml-model-enrichment/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/mark/gitrepos/linkml-model-enrichment/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (rdflib 6.0.2 (/home/mark/gitrepos/linkml-model-enrichment/venv/lib/python3.9/site-packages), Requirement.parse('rdflib>=5.0.0,~=5.0'), {'funowl'})

**Comment by sierra-moxon** [comment]
@turbomam  - I think I can close this as its pre-rdflib 6.0 migration?  Please of course reopen if its still an issue.
