### ISSUE TITLE
Try switching to poetry in this repo

### ISSUE THREAD

**Issue by turbomam** [linkml/schema-automator#23]
- [ ] delete [pre_poetry](https://github.com/linkml/schema-automator/tree/main/pre_poetry) directory
- [ ] close this issue

**Comment by cmungall** [comment]
it looks like this is done?

however, I think we are pinning too tightly to specific versions in dependencies

**Comment by cmungall** [comment]
you also lost all the scripts in setup.cfg....

**Comment by cmungall** [comment]
https://github.com/linkml/linkml-model-enrichment/blob/main/pre_poetry/setup.py

**Comment by turbomam** [comment]
Still need to address functionality of scripts

**Comment by turbomam** [comment]
Also need to reinstate tests
