### ISSUE TITLE
shift GH actions to poetry instead of pip?

### ISSUE THREAD

**Issue by turbomam** [linkml/schema-automator#33]

**Comment by turbomam** [comment]
@cmungall I don't think I have permission to edit GH actions in this repo. (Although I claimed to have disabled one in #4)

**Comment by turbomam** [comment]
Yeah, I have disable and view privileges, but not GH action/workflow edit privileges

**Comment by turbomam** [comment]
The currently problematic workflow is `check-pull-request.yaml` (missing `requirements.txt`)

**Comment by cmungall** [comment]
fixed

**Comment by nlharris** [comment]
Can this be closed?
