### ISSUE TITLE
Choose who owns linkml-model-enrichment in PyPI and what metadata should be used 

### ISSUE THREAD

**Issue by turbomam** [linkml/schema-automator#42]
https://pypi.org/manage/project/linkml-model-enrichment/releases/

review required as part of migration from venv to poetry. Can probably use a lot from [setup.py](setup.py), and then deprecate that

See #23 for moving scripts from `setup.py` to [pyproject.toml](pyproject.toml)

**Comment by sierra-moxon** [comment]
closing as complete.
