### ISSUE TITLE
prototype the OLS term search approach with the FAO soil classes in the MIxS (5?) model 

### ISSUE THREAD

**Issue by turbomam** [linkml/schema-automator#6]
@mslarae13 I placed the results of this mapping exercise in a [google sheet](https://docs.google.com/spreadsheets/d/1Qg2u34-ZchvG2IaIJa43ZCAfedF9LR7MndQZK_ymV4M/edit#gid=2019835930). There's a data dictionary in a seperate tab.

In this case, the mappings are very straightforward. I asked for 5 mappings from ENVO for each soil class. In most cases, there was a match that was identical, except for singular/plural mismatches. In a few other cases, there was no match at all. In those failure cases, there's still one row on the results table, but there's no information about any mappings, and the cosine distance is 1.0. That means that whatever they query was, it is totally different from the empty string that was returned.

Since I request the 5 best mappings, there could be more than one candidate mapping for each soil name from MIxS. If the candidate with rank=1 has a low cosine distance (<0.05) then there's no need to look at the mappings with higher ranks. They're really only useful for brainstorming when the rank 1 candidate mapping wasn't very good.

So one way of looking at the results would be filtering out any row with rank > 1.

This process can now be used for mapping any strings from a model like MIxS to terms form any ontology that is included in the [EBI Ontology Lookup Service](https://www.ebi.ac.uk/ols/index). 

@cmungall and I have also experimented with using [Zooma](https://www.ebi.ac.uk/spot/zooma/) and the [BioPortal Annotator](https://bioportal.bioontology.org/annotator) as back ends. I feel that OLS will give the best mappings to high quality ontologies in almost all cases, but we could return to one of those other providers if necessary.

Please note that future mapping results will probably take the form of slightly different spreadsheets. We are generally using the [SSSOM](https://github.com/mapping-commons/SSSOM) format for these mapping tasks.

**Comment by turbomam** [comment]
Deprecated by #35. Annotating FAO soil class enums works well, but some other enums have PVs that crash the annotator. 

The documentation-like content above should be moved somewhere else and revised if necessary.

**Comment by sierra-moxon** [comment]
closing as deprecated.
